# Playbook for the cloud deployment. Ordering is important as a deployment is sequential. 
# Variables for the cloud configuration are defined globally in ./vars/main.yml

- hosts: cc

- hosts: nc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - nc
  post_tasks:
    - action: setup

- hosts: nc

- hosts: cc
  vars_files:
    - vars/main.yml
  pre_tasks:
    - action: setup
  roles:
    - common
    - cc
    
- hosts: sc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - sc

- hosts: walrus
  vars_files:
    - vars/main.yml
  roles:
    - common
    - walrus
 
- hosts: clc
  vars_files:
    - vars/main.yml
  roles:
    - common
    - clc

- hosts: walrus
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/walrus/tasks/walrus-keys.yml

- hosts: sc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/sc/tasks/sc-keys.yml

- hosts: clc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/clc/tasks/component-reg.yml

- hosts: cc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/cc/tasks/cluster-reg.yml 
  
- hosts: nc
  vars_files:
    - vars/main.yml
  tasks:
  - include: roles/nc/tasks/nc-keys.yml 

- hosts: sc
  post_tasks:
    - action: service name=eucalyptus-cloud state=restarted
    
